defmodule CleatDeployWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :cleat_deploy

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_cleat_deploy_key",
    signing_salt: "wjQ6ykTe",
    same_site: "Lax"
  ]

  @remember_me_cookie "_cleat_deploy_web_user_remember_me"

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [
      connect_info: [session: @session_options, cookies: [{@remember_me_cookie, :signed}]]
    ],
    longpoll: [
      connect_info: [session: @session_options, cookies: [{@remember_me_cookie, :signed}]]
    ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :cleat_deploy,
    gzip: not code_reloading?,
    only: CleatDeployWeb.static_paths(),
    raise_on_missing_only: code_reloading?,
    cache_control_for_etags: if(code_reloading?, do: "no-store, must-revalidate", else: "public")

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :cleat_deploy
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library(),
    body_reader: {CleatDeployWeb.Plugs.CacheBodyReader, :read_body, []}

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug CleatDeployWeb.Router
end
